/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minesweeper;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Omar
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
        updateUI();
    }
    Color grey192 = new Color(192,192,192);
    Color black92 = new Color(92,92,92);
    ImageIcon GenericBackground180x60 = new ImageIcon("src/minesweeper/resources/Generic-Background-180x60.png");
    ImageIcon GenericBackgroundDark180x60 = new ImageIcon("src/minesweeper/resources/Generic-Background-DM-180x60.png");
    ImageIcon GenericBackground440x220 = new ImageIcon("src/minesweeper/resources/Generic-Background-440x220.png");
    ImageIcon GenericBackgroundDark440x220 = new ImageIcon("src/minesweeper/resources/Generic-Background-DM-440x220.png");
    ImageIcon GenericBackground500x500 = new ImageIcon("src/minesweeper/resources/Generic-Background-500x500.png");
    ImageIcon GenericBackgroundDark500x500 = new ImageIcon("src/minesweeper/resources/Generic-Background-DM-500x500.png");
    ImageIcon Bliss = new ImageIcon("src/minesweeper/resources/bliss.jpg");
    ImageIcon msWallpaper = new ImageIcon("src/minesweeper/resources/msWallpaper.jpg");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jamalLabel = new javax.swing.JLabel();
        omarLabel = new javax.swing.JLabel();
        wallyLabel = new javax.swing.JLabel();
        sammyLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        backBtn = new java.awt.Button();
        creditsLabelBackground = new javax.swing.JLabel();
        creditsBody = new javax.swing.JLabel();
        creditsBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jamalLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        jamalLabel.setForeground(new java.awt.Color(92, 92, 92));
        jamalLabel.setText("Jamal Saleh");
        getContentPane().add(jamalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 309, -1, -1));

        omarLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        omarLabel.setForeground(new java.awt.Color(92, 92, 92));
        omarLabel.setText("Omar Arabi");
        getContentPane().add(omarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 256, -1, -1));

        wallyLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        wallyLabel.setForeground(new java.awt.Color(92, 92, 92));
        wallyLabel.setText("Wally El Sayed");
        getContentPane().add(wallyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 203, -1, -1));

        sammyLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        sammyLabel.setForeground(new java.awt.Color(92, 92, 92));
        sammyLabel.setText("Sammy Medawar");
        getContentPane().add(sammyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        creditsLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 37)); // NOI18N
        creditsLabel.setForeground(new java.awt.Color(92, 92, 92));
        creditsLabel.setText("Credits");
        getContentPane().add(creditsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 26, -1, -1));

        backBtn.setBackground(new java.awt.Color(192, 192, 192));
        backBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(92, 92, 92));
        backBtn.setLabel("Back");
        backBtn.setMaximumSize(new java.awt.Dimension(120, 50));
        backBtn.setMinimumSize(new java.awt.Dimension(120, 50));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, 50));

        creditsLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/resources/Generic-Background-180x60.png"))); // NOI18N
        creditsLabelBackground.setToolTipText("");
        getContentPane().add(creditsLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 23, 180, 60));

        creditsBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/resources/Generic-Background-440x220.png"))); // NOI18N
        getContentPane().add(creditsBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 440, 220));

        creditsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/resources/Generic-Background-500x500.png"))); // NOI18N
        getContentPane().add(creditsBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StartScreen n = new StartScreen();
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    private void updateUI(){
        if(Minesweeper.isDarkMode){
            backBtn.setBackground(black92);
            creditsLabelBackground.setIcon(GenericBackgroundDark180x60);
            creditsBody.setIcon(GenericBackgroundDark440x220);
            backBtn.setForeground(grey192);
            creditsLabel.setForeground(grey192);
            sammyLabel.setForeground(grey192);
            wallyLabel.setForeground(grey192);
            omarLabel.setForeground(grey192);
            jamalLabel.setForeground(grey192);
        }
        else {
            backBtn.setBackground(grey192);
            creditsLabelBackground.setIcon(GenericBackground180x60);
            creditsBody.setIcon(GenericBackground440x220);
            backBtn.setForeground(black92);
            creditsLabel.setForeground(black92);
            sammyLabel.setForeground(black92);
            wallyLabel.setForeground(black92);
            omarLabel.setForeground(black92);
            jamalLabel.setForeground(black92);
        }
        
        if(Minesweeper.isDarkMode && Minesweeper.wallpaper.equals("Default"))
            creditsBackground.setIcon(GenericBackgroundDark500x500);
        else if (Minesweeper.isDarkMode == false && Minesweeper.wallpaper.equals("Default"))
            creditsBackground.setIcon(GenericBackground500x500);
        else if (Minesweeper.wallpaper.equals("Bliss"))
            creditsBackground.setIcon(Bliss);
        else if (Minesweeper.wallpaper.equals("Minesweeper Art"))
            creditsBackground.setIcon(msWallpaper);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button backBtn;
    private javax.swing.JLabel creditsBackground;
    private javax.swing.JLabel creditsBody;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel creditsLabelBackground;
    private javax.swing.JLabel jamalLabel;
    private javax.swing.JLabel omarLabel;
    private javax.swing.JLabel sammyLabel;
    private javax.swing.JLabel wallyLabel;
    // End of variables declaration//GEN-END:variables
}
