/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minesweeper;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Omar
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        updateUI();
        
    }
    Color grey192 = new Color(192,192,192);
    Color black92 = new Color(92,92,92);
    ImageIcon GenericBackground500x500 = new ImageIcon("src/minesweeper/resources/Generic-Background-500x500.png");
    ImageIcon GenericBackgroundDark500x500 = new ImageIcon("src/minesweeper/resources/Generic-Background-DM-500x500.png");
    ImageIcon Bliss = new ImageIcon("src/minesweeper/resources/bliss.jpg");
    ImageIcon msWallpaper = new ImageIcon("src/minesweeper/resources/msWallpaper.jpg");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditBtn = new java.awt.Button();
        playBtn = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        quitGameBtn = new java.awt.Button();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creditBtn.setBackground(new java.awt.Color(192, 192, 192));
        creditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        creditBtn.setForeground(new java.awt.Color(92, 92, 92));
        creditBtn.setLabel("Credits");
        creditBtn.setMaximumSize(new java.awt.Dimension(120, 50));
        creditBtn.setMinimumSize(new java.awt.Dimension(120, 50));
        creditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(creditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 50));

        playBtn.setBackground(new java.awt.Color(192, 192, 192));
        playBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        playBtn.setForeground(new java.awt.Color(92, 92, 92));
        playBtn.setLabel("Play");
        playBtn.setMaximumSize(new java.awt.Dimension(120, 50));
        playBtn.setMinimumSize(new java.awt.Dimension(120, 50));
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        getContentPane().add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/resources/MSLogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 400, 195));

        quitGameBtn.setBackground(new java.awt.Color(192, 192, 192));
        quitGameBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitGameBtn.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        quitGameBtn.setForeground(new java.awt.Color(92, 92, 92));
        quitGameBtn.setLabel("Quit Game");
        quitGameBtn.setMaximumSize(new java.awt.Dimension(120, 50));
        quitGameBtn.setMinimumSize(new java.awt.Dimension(120, 50));
        quitGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitGameBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quitGameBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 120, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/resources/Generic-Background-500x500.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBtnActionPerformed
        Credits n = new Credits();
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_creditBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        MainMenu n = new MainMenu();
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_playBtnActionPerformed

    private void quitGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitGameBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitGameBtnActionPerformed
    private void updateUI() {
        if (Minesweeper.isDarkMode) {
            playBtn.setBackground(black92);
            playBtn.setForeground(grey192);
            creditBtn.setBackground(black92);
            creditBtn.setForeground(grey192);
            quitGameBtn.setBackground(black92);
            quitGameBtn.setForeground(grey192);
        }
        else {
            playBtn.setBackground(grey192);
            playBtn.setForeground(black92);
            creditBtn.setBackground(grey192);
            creditBtn.setForeground(black92);
            quitGameBtn.setBackground(grey192);
            quitGameBtn.setForeground(black92);
        }
        if(Minesweeper.isDarkMode && Minesweeper.wallpaper.equals("Default"))
            background.setIcon(GenericBackgroundDark500x500);
        else if (Minesweeper.isDarkMode == false && Minesweeper.wallpaper.equals("Default"))
            background.setIcon(GenericBackground500x500);
        else if (Minesweeper.wallpaper.equals("Bliss"))
            background.setIcon(Bliss);
        else if (Minesweeper.wallpaper.equals("Minesweeper Art"))
            background.setIcon(msWallpaper);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private java.awt.Button creditBtn;
    private javax.swing.JLabel jLabel1;
    private java.awt.Button playBtn;
    private java.awt.Button quitGameBtn;
    // End of variables declaration//GEN-END:variables
}
